use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'ZhangHongHomeModule_Example' do
  pod 'ZhangHongHomeModule', :path => '../'
  pod 'ZhangHongBaseModule'

  target 'ZhangHongHomeModule_Tests' do
    inherit! :search_paths

    
  end
end
