use_frameworks!

platform :ios, '8.0'

target 'ZhangHongHomeModule_Example' do
  pod 'ZhangHongHomeModule', :path => '../'

  target 'ZhangHongHomeModule_Tests' do
    inherit! :search_paths

    
  end
end
